### ISSUE TITLE
generate readme

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#11]
@nathanchance noted in #9 that we could generate info in the README, such as the usage and even the badge URLs

**Comment by msfjarvis** [comment]
I'll take a look.

**Comment by msfjarvis** [comment]
Bunch of things we need to figure out to make this work.

- If a PR changes `generator.yml`, do we want the workflow to update the same PR with the newly generated files?
- Running a workflow on pull requests that also has access to a `GITHUB_TOKEN` with write access to our repository is a security disaster, so we can't exactly do that.
- To make the 'update-the-PR' situation work, we will require slight indirection where a 'tests' workflow will run first, then its completion will trigger the [`workflow_run`](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_run) event which can then regenerate our workflows and README. However, that'll require said tests workflow to exist, which it does not at the moment.

<hr />

- If we don't update the actual PR, then we eliminate a lot of these problems. Our workflow can then simply run with this trigger

```yaml
on:
  push:
    branches: ["main"]
    paths: ["generator.yml"]
```

and then open another PR if the workflows/README needed to be updated. This approach gets rid of the 
a) security issues, because the workflow does not execute unreviewed code
b) automation complexity, as the push event and paths filter mean we don't need to check for changed files ourselves and we won't have any potential issues with PRs from people who turn off the 'Allow maintainer changes' option when opening, thus making it impossible for us to push.

**Comment by nathanchance** [comment]
Updating pull requests is not really what I had in mind. I was just thinking of adding a shell script like `generate.sh` that would run the `.py` scripts how they should be run then maybe using GitHub Actions to run that whenever `generator.yml` was changed to make sure that all files are up to date and erroring if there is a difference, leaving it up to the user to actually update them properly. However, maybe just adding a workflow to automatically update the workflow files is the way to go instead? I do not have a strong preference.

**Comment by msfjarvis** [comment]
> Updating pull requests is not really what I had in mind. I was just thinking of adding a shell script like `generate.sh` that would run the `.py` scripts how they should be run then maybe using GitHub Actions to run that whenever `generator.yml` was changed to make sure that all files are up to date and erroring if there is a difference, leaving it up to the user to actually update them properly. However, maybe just adding a workflow to automatically update the workflow files is the way to go instead? I do not have a strong preference.

Ah, I misunderstood it then. What you have in mind is rather easy to achieve, I'll get it done over this weekend.

**Comment by nickdesaulniers** [comment]
> then maybe using GitHub Actions to run 

Or a git precommit hook?

**Comment by nathanchance** [comment]
There are two aspect to this issue:

1. Making sure all the GitHub Actions and TuxSuite files are up to date with every change to `generator.yml`, which was taken care of with https://github.com/ClangBuiltLinux/continuous-integration2/pull/300.
2. Automatically generating the badges in the README, which will be handled by https://github.com/ClangBuiltLinux/continuous-integration2/pull/301. It won't be automatic but I don't think that is a bad thing.

Once https://github.com/ClangBuiltLinux/continuous-integration2/pull/301 is merged, this can be closed.
